source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GlyuckDataGrid_Example', :exclusive => true do
  pod "GlyuckDataGrid", :path => "../"
end

target 'GlyuckDataGrid_Tests', :exclusive => true do
  pod "GlyuckDataGrid", :path => "../"

  pod 'Quick', '~> 0.3.0'
  pod 'Nimble', '~> 1.0.0'
#  pod 'FBSnapshotTestCase'
#  pod 'Nimble-Snapshots'
end
