source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GlyuckDataGrid_Example', :exclusive => true do
  pod "GlyuckDataGrid", :path => "../"
end

target 'GlyuckDataGrid_Tests', :exclusive => true do
  pod "GlyuckDataGrid", :path => "../"

  pod 'Quick'
  pod 'Nimble', '2.0.0-rc.2'
#  pod 'FBSnapshotTestCase'
#  pod 'Nimble-Snapshots'
end
